nix: use clang 15 for the ebpf build
Required as on nixos-unstable:
	error: clang_14 has been removed, as it is unmaintained and obsolete

We can't simply use the clang_15 as we now need to use clang-unwrapped.

Additionally, we now need kernel headers on NixOS.